jsout={
    "Jinja": {
        "template": ""
    },
    "generic_present": False,
    "entity_name":"entity",
    "LRGates": {
    #in the form G1:[i1,i2], G2:[i2,i3], "G3": ["G1","G2"]
    },
    "Gates": [],
    #in the form [G1,G2,G3] 
    "Types": {
        #in the form "G1": { "type": "AND","in": 2,"out": 1},
    },
    "Terminals": {
        #in the form "in": 4, "out": 1
    },
    "Link": {
        #Generated by Code generator
    }
    
}